services:
  backend:
    image: bite-backend
    container_name: bite_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8080:8080
  frontend:
    image: bite-frontend
    container_name: bite_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    ports:
      - 3000:3000