on:
    push:

defaults:
   run:
        working-directory: frontend

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
        - run: node --version
        - name: npm ci
          working-directory: frontend
          run: npm ci
